apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
    - name: "4180"
      port: 4180
      targetPort: 4180
  selector:
    io.kompose.service: oauth2-proxy
