apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: observer
  name: observer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: observer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/cloudcomputing-ccnet: "true"
        io.kompose.service: observer
    spec:
      containers:
        - image: observernode
          name: observer
      restartPolicy: Always
