apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: worker1
  name: worker1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/cloudcomputing-ccnet: "true"
        io.kompose.service: worker1
    spec:
      containers:
        - image: workernode
          name: worker1
      restartPolicy: Always
